
services:
  mysql:
    image: mysql:8
    container_name: sp-mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mechain
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  initdb:
    container_name: initdb
    image: "zkmelabs/mechain-storage-provider"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - "./sp.json:/workspace/sp.json:Z"
      - "./deployment/dockerup:/workspace/deployment/dockerup:Z"
      - "local-env:/workspace/deployment/dockerup/local_env"
    working_dir: "/workspace/deployment/dockerup"
    command: >
      bash -c "
      rm -f initdb_done &&
      mkdir -p /workspace/build &&
      cp /usr/bin/mechain-sp /workspace/build/mechain-sp &&
      bash localup.sh --generate /workspace/sp.json root mechain mysql:3306 && 
      bash localup.sh --reset &&
      touch initdb_done && 
      sleep infinity
      "
    healthcheck:
      test: ["CMD-SHELL", "test -f /workspace/deployment/dockerup/initdb_done && echo 'OK' || exit 1"]
      interval: 10s
      retries: 5
    restart: "on-failure"
  node0:
    container_name: mechain-sp-0
    depends_on:
      initdb:
        condition: service_healthy
    image: "zkmelabs/mechain-storage-provider"
    ports:
      - "9033:9033"
      - "9063:9063"
      - "9400:9400"
      - "9401:9401"
      - "9402:9402"
    volumes:
      - "local-env:/app"
    command: >
      /usr/bin/mechain-sp --config /app/sp0/config.toml
  node1:
    container_name: mechain-sp-1
    depends_on:
      initdb:
        condition: service_healthy
    image: "zkmelabs/mechain-storage-provider"
    ports:
      - "9034:9033"
      - "9064:9063"
      - "10400:9400"
      - "10401:9401"
      - "10402:9402"
    volumes:
      - "local-env:/app"
    command: >
      /usr/bin/mechain-sp --config /app/sp1/config.toml
  node2:
    container_name: mechain-sp-2
    depends_on:
      initdb:
        condition: service_healthy
    image: "zkmelabs/mechain-storage-provider"
    ports:
      - "9035:9033"
      - "9065:9063"
      - "11400:9400"
      - "11401:9401"
      - "11402:9402"
    volumes:
      - "local-env:/app"
    command: >
      /usr/bin/mechain-sp --config /app/sp2/config.toml
  node3:
    container_name: mechain-sp-3
    depends_on:
      initdb:
        condition: service_healthy
    image: "zkmelabs/mechain-storage-provider"
    ports:
      - "9036:9033"
      - "9066:9063"
      - "12400:9400"
      - "12401:9401"
      - "12402:9402"
    volumes:
      - "local-env:/app"
    command: >
      /usr/bin/mechain-sp --config /app/sp3/config.toml
  node4:
    container_name: mechain-sp-4
    depends_on:
      initdb:
        condition: service_healthy
    image: "zkmelabs/mechain-storage-provider"
    ports:
      - "9037:9033"
      - "9067:9063"
      - "13400:9400"
      - "13401:9401"
      - "13402:9402"
    volumes:
      - "local-env:/app"
    command: >
      /usr/bin/mechain-sp --config /app/sp4/config.toml
  node5:
    container_name: mechain-sp-5
    depends_on:
      initdb:
        condition: service_healthy
    image: "zkmelabs/mechain-storage-provider"
    ports:
      - "9038:9033"
      - "9068:9063"
      - "14400:9400"
      - "14401:9401"
      - "14402:9402"
    volumes:
      - "local-env:/app"
    command: >
      /usr/bin/mechain-sp --config /app/sp5/config.toml
  node6:
    container_name: mechain-sp-6
    depends_on:
      initdb:
        condition: service_healthy
    image: "zkmelabs/mechain-storage-provider"
    ports:
      - "9039:9033"
      - "9069:9063"
      - "15400:9400"
      - "15401:9401"
      - "15402:9402"
    volumes:
      - "local-env:/app"
    command: >
      /usr/bin/mechain-sp --config /app/sp6/config.toml
  node7:
    container_name: mechain-sp-7
    depends_on:
      initdb:
        condition: service_healthy
    image: "zkmelabs/mechain-storage-provider"
    ports:
      - "9040:9033"
      - "9070:9063"
      - "16400:9400"
      - "16401:9401"
      - "16402:9402"
    volumes:
      - "local-env:/app"
    command: >
      /usr/bin/mechain-sp --config /app/sp7/config.toml
volumes:
  db-data:
  local-env:
