
services:
  mysql:
    image: mysql:8
    networks:
      - mechain-network
    container_name: sp-mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mechain
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  init:
    container_name: init-sp
    image: "zkmelabs/mechain-storage-provider"
    networks:
      - mechain-network    
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - "./deployment/dockerup/sp.json:/workspace/sp.json:Z"
      - "./deployment/dockerup:/workspace/deployment/dockerup:Z"
      - "local-env:/workspace/deployment/dockerup/local_env"
    working_dir: "/workspace/deployment/dockerup"
    command: >
      bash -c "
      rm -f init_done &&
      mkdir -p /workspace/build &&
      cp /usr/bin/mechain-sp /workspace/build/mechain-sp &&
      bash localup.sh --generate /workspace/sp.json root mechain mysql:3306 && 
      bash localup.sh --reset &&
      touch init_done && 
      sleep infinity
      "
    healthcheck:
      test: ["CMD-SHELL", "test -f /workspace/deployment/dockerup/init_done && echo 'OK' || exit 1"]
      interval: 10s
      retries: 5
    restart: "on-failure"
  spnode-0:
    container_name: mechain-sp-0
    depends_on:
      init:
        condition: service_healthy
    image: "zkmelabs/mechain-storage-provider"
    networks:
      - mechain-network
    ports:
      - "9033:9033"
      - "9063:9063"
      - "9400:9400"
      - "9401:9401"
      - "9402:9402"
    volumes:
      - "local-env:/app"
    working_dir: "/app/sp0/"
    command: >
      ./mechain-sp0 --config config.toml </dev/null >log.txt 2>&1 &
  spnode-1:
    container_name: mechain-sp-1
    depends_on:
      init:
        condition: service_healthy
    image: "zkmelabs/mechain-storage-provider"
    networks:
      - mechain-network
    ports:
      - "9034:9033"
      - "9064:9063"
      - "10400:9400"
      - "10401:9401"
      - "10402:9402"
    volumes:
      - "local-env:/app"
    working_dir: "/app/sp1/"
    command: >
      ./mechain-sp1 --config config.toml </dev/null >log.txt 2>&1 &
  spnode-2:
    container_name: mechain-sp-2
    depends_on:
      init:
        condition: service_healthy
    image: "zkmelabs/mechain-storage-provider"
    networks:
      - mechain-network
    ports:
      - "9035:9033"
      - "9065:9063"
      - "11400:9400"
      - "11401:9401"
      - "11402:9402"
    volumes:
      - "local-env:/app"
    working_dir: "/app/sp2/"
    command: >
      ./mechain-sp2 --config config.toml </dev/null >log.txt 2>&1 &
volumes:
  db-data:
  local-env:
networks:
  mechain-network:
    external: true
