# For developer
name: Deploy for devint
on:
  push:
    branches:
      - develop
      - kevin/cicd

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: zkmelabs
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: zkmelabs/mechain-storage-provider:develop
          cache-to: type=gha
          cache-from: type=gha


  deploy-with-k8s:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: "Deploy new StatefulSet"
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG_DEV }}
        with:
          args: -n mechain-dev rollout restart statefulset mechain-storage-provider

      - name: "Check StatefulSet"
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG_DEV }}
        with:
          args: -n mechain-dev wait --for=condition=Available statefulset/mechain-storage-provider --timeout=300s
