name: Push to Docker Hub

on:
  workflow_call:
    inputs:
      tags:
        description: Image tags, example. zkmelabs/mechain-storage-provider:develop
        required: true
        type: string
      platforms:
        description: Image platforms (you can specify multiple platforms separated by comma)
        required: false
        type: string
        default: linux/amd64

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Git fetch everything
        run: git fetch --prune --unshallow

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: zkmelabs
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: ${{ inputs.platforms }}
          tags: ${{ inputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
